matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      before_script:
        - cd frontend #Change directory into correct frontend folder
        - npm install
      cache:
        directories:
          - node_modules #Cache node_modules for faster builds
        script:
          - npm test #Runs Tests

    - language: go
      script:
        - cd backend #Run go test in backend folder
        - go test ./... #Run all go test


notifications:
  email:
    - cochranjm@appstate.edu